#############################################################################
# Generated by PAGE version 8.1f
#  in conjunction with Tcl version 8.6
#  May 01, 2024 07:11:12 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    information_png "./graphics/information.png" 
    question_png "./graphics/question.png" 
    system_shutdown_png "./graphics/system-shutdown.png" 
    edit_find_png "./graphics/edit-find.png" 
    accessories_text_editor_png "./graphics/accessories-text-editor.png" 
    media_floppy_png "./graphics/media-floppy.png" 
    edit_delete_png "./graphics/edit-delete.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) page-cornsilkdark



proc vTclWindow.top49 {base} {
    global vTcl
    if {$base == ""} {
        set base .top49
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background cornsilk4 -container 0 \
        -height 0 -highlightbackground cornsilk4 -highlightcolor black \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 1000x689+767+357
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Sphinx Demo 1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::frame "$top.tFr50" \
        -borderwidth 2 -relief sunken -width 125 -height 75 -style "" 
    vTcl:DefineAlias "$top.tFr50" "FrameBar" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::button "$site_3_0.men53" \
        -command "on_btnAbout" -default normal -takefocus ttk::takefocus \
        -underline -1 -image information_png -compound none -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.men53" "btnAbout" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.men53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {About}
    }
    ttk::button "$site_3_0.men52" \
        -command "on_btnHelp" -default normal -takefocus ttk::takefocus \
        -underline -1 -width 42 -image question_png -compound none \
        -state normal -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.men52" "btnHelp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.men52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    ttk::button "$site_3_0.tBu51" \
        -command "on_btnExit" -default normal -takefocus ttk::takefocus \
        -underline -1 -image system_shutdown_png -compound none -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu51" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit}
    }
    ttk::label "$site_3_0.tLa55" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief flat \
        -anchor e -justify left -text "Available Themes:" -underline -1 \
        -width 198 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa55" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo54" \
        -height 10 -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -justify left -state normal -textvariable "comboThemes" \
        -validate none -width 20 -takefocus ttk::takefocus -style "" 
    vTcl:DefineAlias "$site_3_0.tCo54" "TComboboxThemes" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.men53 \
        -in $site_3_0 -x 828 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men52 \
        -in $site_3_0 -x 890 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 947 -y 3 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 200 -y 10 -width 198 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo54 \
        -in $site_3_0 -x 410 -y 10 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr50
    ttk::frame "$top.tFr57" \
        -borderwidth 2 -relief sunken -width 125 -height 75 -style "" 
    vTcl:DefineAlias "$top.tFr57" "FrameStatus" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr57
    ttk::label "$site_3_0.tLa58" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief sunken \
        -anchor center -justify left -textvariable "::StatusTime" \
        -underline -1 -width 168 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa58" "LabelStatusTime" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.men59" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief sunken \
        -anchor center -justify left -textvariable "::StatusInfo1" \
        -underline -1 -width 398 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.men59" "LabelStatusInfo1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.men60" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief sunken \
        -anchor center -justify left -textvariable "::StatusInfo2" \
        -underline -1 -width 398 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.men60" "LabelStatusInfo2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 824 -y 2 -width 168 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men59 \
        -in $site_3_0 -x 2 -y 2 -width 423 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men60 \
        -in $site_3_0 -x 425 -y 2 -width 398 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr57
    vTcl::widgets::core::popup::createCmd "$top.pop67" \
        -activebackground beige -activeborderwidth 1 -activeforeground black \
        -background cornsilk4 -borderwidth 1 -cursor arrow \
        -disabledforeground #68665a -font "-family {DejaVu Sans} -size 10" \
        -foreground black -relief raised -selectcolor #000000 -takefocus 0 \
        -tearoff 1 -type normal 
    global vTcl
    set val vTcl($top.pop67,-proc)
    set vTcl($top.pop67,-proc) popup1
    namespace eval ::widgets::$top.pop67 {}
    set ::widgets::$top.pop67::ClassOption(-proc) popup1
    set ::widgets::$top.pop67::options(-proc) popup1
    set ::widgets::$top.pop67::save(-proc) 1
    vTcl:DefineAlias "$top.pop67" "Popupmenu1" vTcl:WidgetProc "" 1
    $top.pop67 add command \
        -command "#lambda : on_popCopy(args)" -compound left \
        -font "-family {DejaVu Sans} -size 12" -label "Copy" 
    $top.pop67 add command \
        -command "#lambda : on_popCut(args)" -compound left \
        -font "-family {DejaVu Sans} -size 12" -label "Cut" 
    $top.pop67 add command \
        -command "#lambda : on_popClear(args)" -compound left \
        -font "-family {DejaVu Sans} -size 12" -label "Clear" 
    $top.pop67 add separator \
        
    $top.pop67 add command \
        -command "#lambda : on_popPaste(args)" -compound left \
        -font "-family {DejaVu Sans} -size 12" -label "Paste" 
    $top.pop67 add separator \
        
    $top.pop67 add command \
        -command "#lambda : on_popCloseMenu(args)" -compound left \
        -font "-family {DejaVu Sans} -size 12" -label "Close Menu" 
    ttk::frame "$top.tFr56" \
        -borderwidth 2 -relief sunken -width 996 -height 575 -style "" 
    vTcl:DefineAlias "$top.tFr56" "FrameMain" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr56
    ttk::label "$site_3_0.tLa64" \
        -font "-family {DejaVu Sans} -size 10 -weight bold" -relief flat \
        -anchor e -justify left -text "First Name:" -underline -1 -width 130 \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.tLa64" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.men65" \
        -font "-family {DejaVu Sans} -size 10 -weight bold" -relief flat \
        -anchor e -justify left -text "Middle Initial:" -underline -1 \
        -width 130 -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.men65" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.men66" \
        -font "-family {DejaVu Sans} -size 10 -weight bold" -relief flat \
        -anchor e -justify left -text "Last Name:" -underline -1 -width 130 \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.men66" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.men69" \
        -font "-family {DejaVu Sans} -size 10 -weight bold" -relief flat \
        -anchor e -justify left -text "Emp ID:" -underline -1 -width 130 \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$site_3_0.men69" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu70" \
        -command "on_btnFind" -default normal -takefocus ttk::takefocus \
        -underline -1 -image edit_find_png -compound left -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu70" "btnFind" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu70 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Find}
    }
    ttk::button "$site_3_0.tBu71" \
        -command "on_btnEdit" -default normal -takefocus ttk::takefocus \
        -underline -1 -image accessories_text_editor_png -compound left \
        -state normal -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu71" "btnEdit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu71 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Edit Record}
    }
    ttk::button "$site_3_0.tBu72" \
        -command "on_btnSave" -default normal -takefocus ttk::takefocus \
        -underline -1 -image media_floppy_png -compound left -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu72" "btnSave" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu72 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save}
    }
    ttk::button "$site_3_0.tBu73" \
        -command "on_btnDelete" -default normal -takefocus ttk::takefocus \
        -underline -1 -image edit_delete_png -compound left -state normal \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_3_0.tBu73" "btnDelete" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu73 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete}
    }
    ttk::entry "$site_3_0.tEn68" \
        -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -justify left -state normal -validate none -width 20 \
        -takefocus ttk::takefocus -cursor xterm -style "" 
    vTcl:DefineAlias "$site_3_0.tEn68" "TEntry4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tEn68 <Button-3> {
        lambda e: popup1(e,1)
    }
    ttk::entry "$site_3_0.tEn61" \
        -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -justify left -state normal -validate none -width 20 \
        -takefocus ttk::takefocus -cursor xterm -style "" 
    vTcl:DefineAlias "$site_3_0.tEn61" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tEn61 <Button-3> {
        lambda e: popup1(e,2)
    }
    ttk::entry "$site_3_0.tEn62" \
        -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -justify left -state normal -validate none -width 20 \
        -takefocus ttk::takefocus -cursor xterm -style "" 
    vTcl:DefineAlias "$site_3_0.tEn62" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tEn62 <Button-3> {
        lambda e: popup1(e,3)
    }
    ttk::entry "$site_3_0.tEn63" \
        -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -justify left -state normal -validate none -width 20 \
        -takefocus ttk::takefocus -cursor xterm -style "" 
    vTcl:DefineAlias "$site_3_0.tEn63" "TEntry3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tEn63 <Button-3> {
        lambda e: popup1(e,4)
    }
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 92 -y 81 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men65 \
        -in $site_3_0 -x 92 -y 120 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men66 \
        -in $site_3_0 -x 92 -y 161 -width 130 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.men69 \
        -in $site_3_0 -x 90 -y 20 -width 130 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu70 \
        -in $site_3_0 -x 430 -y 10 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu71 \
        -in $site_3_0 -x 610 -y 10 -width 42 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu72 \
        -in $site_3_0 -x 684 -y 10 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu73 \
        -in $site_3_0 -x 751 -y 10 -width 42 -relwidth 0 -height 42 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn68 \
        -in $site_3_0 -x 230 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tEn61 \
        -in $site_3_0 -x 230 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.tEn62 \
        -in $site_3_0 -x 230 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.tEn63 \
        -in $site_3_0 -x 230 -y 160 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr56
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr50 \
        -in $top -x 2 -y 2 -width 996 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 2 -y 632 -width 996 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr56 \
        -in $top -x 2 -y 57 -width 996 -relwidth 0 -height 575 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top49 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

